In [1]:
import numpy as np
import pandas as pd

In [2]:
# 7.1 处理缺失值 Missing values
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [3]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [5]:
# 7.1.1 过滤缺失值
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [6]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [8]:
# all rows with NA are cleaned
cleaned

0    1    2
0  1.0  6.5  3.0

In [9]:
# rows with all NA are cleaned
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [10]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [11]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0  0.961394       NaN       NaN
1  0.240744       NaN       NaN
2  2.279427       NaN -1.240680
3 -0.443691       NaN -0.817052
4  0.474927 -0.559971 -0.617343
5  1.489080  0.687235 -0.274241
6 -0.731667 -1.150007  1.125096

In [13]:
df.dropna()

0         1         2
4  0.474927 -0.559971 -0.617343
5  1.489080  0.687235 -0.274241
6 -0.731667 -1.150007  1.125096

In [14]:
df.dropna(thresh=2)

0         1         2
2  2.279427       NaN -1.240680
3 -0.443691       NaN -0.817052
4  0.474927 -0.559971 -0.617343
5  1.489080  0.687235 -0.274241
6 -0.731667 -1.150007  1.125096

In [15]:
# 7.1.2 补全缺失值
df.fillna(0)

0         1         2
0  0.961394  0.000000  0.000000
1  0.240744  0.000000  0.000000
2  2.279427  0.000000 -1.240680
3 -0.443691  0.000000 -0.817052
4  0.474927 -0.559971 -0.617343
5  1.489080  0.687235 -0.274241
6 -0.731667 -1.150007  1.125096

In [16]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.961394  0.500000  0.000000
1  0.240744  0.500000  0.000000
2  2.279427  0.500000 -1.240680
3 -0.443691  0.500000 -0.817052
4  0.474927 -0.559971 -0.617343
5  1.489080  0.687235 -0.274241
6 -0.731667 -1.150007  1.125096

In [17]:
_ = df.fillna(0, inplace=True)
df

0         1         2
0  0.961394  0.000000  0.000000
1  0.240744  0.000000  0.000000
2  2.279427  0.000000 -1.240680
3 -0.443691  0.000000 -0.817052
4  0.474927 -0.559971 -0.617343
5  1.489080  0.687235 -0.274241
6 -0.731667 -1.150007  1.125096

In [18]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0 -0.199330 -0.103434  1.521558
1 -0.177864 -0.956427  0.769876
2 -0.074566       NaN -0.416850
3  1.381113       NaN -0.493176
4  0.805589       NaN       NaN
5 -0.907331       NaN       NaN

In [19]:
df.fillna(method='ffill')

0         1         2
0 -0.199330 -0.103434  1.521558
1 -0.177864 -0.956427  0.769876
2 -0.074566 -0.956427 -0.416850
3  1.381113 -0.956427 -0.493176
4  0.805589 -0.956427 -0.493176
5 -0.907331 -0.956427 -0.493176

In [20]:
df.fillna(method='ffill', limit=2)

0         1         2
0 -0.199330 -0.103434  1.521558
1 -0.177864 -0.956427  0.769876
2 -0.074566 -0.956427 -0.416850
3  1.381113 -0.956427 -0.493176
4  0.805589       NaN -0.493176
5 -0.907331       NaN -0.493176

In [21]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [22]:
# 7.2 数据转换
# 7.2.1 删除重复值 duplicates
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [23]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [24]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [25]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [26]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [27]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [29]:
# 7.2.2 使用函数或映射进行数据转换
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [31]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [32]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [33]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [34]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [35]:
# 7.2.3 替代值
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [36]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [37]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [38]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [41]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [42]:
# 7.2.4 重命名轴索引
data = pd.DataFrame(np.arange(12).reshape(3,4),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [43]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [45]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [49]:
data.rename(index={'OHIO': 'INDIANA', 'COLO': 'ASD'},
            columns={'three': 'peekaboo', 'one': 1})

1  two  peekaboo  four
INDIANA  0    1         2     3
ASD      4    5         6     7
NEW      8    9        10    11

In [51]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [53]:
# 7.2.5 离散化和分箱
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [54]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [55]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [56]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [57]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [58]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [59]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.55, 0.73], (0.18, 0.36], (0.36, 0.55], (0.36, 0.55], (0.55, 0.73], ..., (0.73, 0.91], (0.55, 0.73], (0.36, 0.55], (0.73, 0.91], (0.36, 0.55]]
Length: 20
Categories (4, interval[float64]): [(0.18, 0.36] < (0.36, 0.55] < (0.55, 0.73] < (0.73, 0.91]]

In [60]:
data = np.random.randn(1000) # normally distributed
cats = pd.qcut(data, 4) # quantile quartile cut
cats

[(-0.681, 0.0235], (-0.681, 0.0235], (0.793, 3.554], (-0.681, 0.0235], (0.793, 3.554], ..., (-0.681, 0.0235], (-2.695, -0.681], (-2.695, -0.681], (-0.681, 0.0235], (-0.681, 0.0235]]
Length: 1000
Categories (4, interval[float64]): [(-2.695, -0.681] < (-0.681, 0.0235] < (0.0235, 0.793] < (0.793, 3.554]]

In [61]:
pd.value_counts(cats)

(-2.695, -0.681]    250
(-0.681, 0.0235]    250
(0.0235, 0.793]     250
(0.793, 3.554]      250
dtype: int64

In [62]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.307, 0.0235], (-1.307, 0.0235], (1.342, 3.554], (-1.307, 0.0235], (0.0235, 1.342], ..., (-1.307, 0.0235], (-2.695, -1.307], (-1.307, 0.0235], (-1.307, 0.0235], (-1.307, 0.0235]]
Length: 1000
Categories (4, interval[float64]): [(-2.695, -1.307] < (-1.307, 0.0235] < (0.0235, 1.342] < (1.342, 3.554]]

In [63]:
# 7.2.6 检测和过滤异常值
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.039624    -0.035801     0.017509     0.017338
std       1.014949     0.988272     1.029287     0.989163
min      -3.371430    -3.031936    -3.555172    -3.262374
25%      -0.731985    -0.723396    -0.697426    -0.648678
50%      -0.035009    -0.033193     0.050980    -0.004141
75%       0.602487     0.584050     0.702479     0.687790
max       3.443480     2.970170     3.534203     3.048667

In [64]:
col = data[2]
col[np.abs(col) > 3]

15     3.534203
114   -3.555172
229   -3.083044
292    3.024691
Name: 2, dtype: float64

In [67]:
# rows with number greater than 3 or less than -3
data[(np.abs(data) > 3).any(1)]

0         1         2         3
15  -0.359774 -0.065285  3.534203 -1.538586
29   3.345894  0.313062 -1.931256 -0.170774
114  2.028850  0.947390 -3.555172 -0.523923
217  3.013721  0.047497 -0.153701 -0.097990
229 -1.844231 -0.214186 -3.083044  1.090618
292  0.108414  0.486073  3.024691  1.041394
409  3.443480  0.312541 -0.709391  2.190181
567 -3.217834 -0.913552  1.577788  0.307430
703 -0.117341 -1.826712  1.209859  3.048667
729 -0.548711 -0.674762 -0.369049 -3.262374
852 -0.288282 -0.644710 -1.034135 -3.046728
974 -1.389469 -3.022359 -2.064764 -0.414976
981 -0.556714 -3.031936  0.071766  0.254336
999 -3.371430 -0.100426 -0.354375  0.464193

In [68]:
# limit (-3, 3)
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.039838    -0.035747     0.017589     0.017598
std       1.010564     0.988108     1.025493     0.988034
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.731985    -0.723396    -0.697426    -0.648678
50%      -0.035009    -0.033193     0.050980    -0.004141
75%       0.602487     0.584050     0.702479     0.687790
max       3.000000     2.970170     3.000000     3.000000

In [69]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0  1.0 -1.0
1 -1.0  1.0  1.0 -1.0
2  1.0  1.0 -1.0 -1.0
3 -1.0  1.0  1.0  1.0
4  1.0 -1.0 -1.0 -1.0

In [75]:
# 7.2.7 置换和随机抽样
df = pd.DataFrame(np.arange(5 * 4).reshape(5, 4))
sampler = np.random.permutation(5)
sampler

array([4, 3, 1, 0, 2])

In [76]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [77]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11

In [78]:
df.sample(n=3)

0   1   2   3
3  12  13  14  15
4  16  17  18  19
1   4   5   6   7

In [79]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)
draws

0    5
3    6
2   -1
1    7
0    5
3    6
4    4
1    7
0    5
2   -1
dtype: int64

In [80]:
# 7.2.8 计算指标/虚拟变量
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [82]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [86]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('datasets/movielens/movies.dat', sep='::',
                       header=None, names=mnames, engine='python')
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [102]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))

genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [103]:
# Zero matrix
zero_matrix = np.zeros((len(movies), len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres, dtype='int')
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [104]:
dummies.head()

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  Action  \
0          0           0       0          0        0        0      0       0   
1          0           0       0          0        0        0      0       0   
2          0           0       0          0        0        0      0       0   
3          0           0       0          0        0        0      0       0   
4          0           0       0          0        0        0      0       0   

   Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  Mystery  \
0      0         0       0       0            0    0        0        0   
1      0         0       0       0            0    0        0        0   
2      0         0       0       0            0    0        0        0   
3      0         0       0       0            0    0        0        0   
4      0         0       0       0            0    0        0        0   

   Film-Noir  Western  
0          0        0  
1          0        0  
2          0        0  
3          0        0  
4          0        0

In [105]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [109]:
# Traverse all movies
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

movies_windic = movies[['movie_id', 'title']].join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]

movie_id                            1
title                Toy Story (1995)
Genre_Animation                     1
Genre_Children's                    1
Genre_Comedy                        1
Genre_Adventure                     0
Genre_Fantasy                       0
Genre_Romance                       0
Genre_Drama                         0
Genre_Action                        0
Genre_Crime                         0
Genre_Thriller                      0
Genre_Horror                        0
Genre_Sci-Fi                        0
Genre_Documentary                   0
Genre_War                           0
Genre_Musical                       0
Genre_Mystery                       0
Genre_Film-Noir                     0
Genre_Western                       0
Name: 0, dtype: object

In [116]:
np.random.seed(12345)

In [117]:
values = np.random.rand(10).round(4)
values

array([0.9296, 0.3164, 0.1839, 0.2046, 0.5677, 0.5955, 0.9645, 0.6532,
       0.7489, 0.6536])

In [118]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [119]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [ ]:
# 7.3 字符串操作
